services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root2025
      MYSQL_DATABASE: hackfest
      MYSQL_USER: hacker
      MYSQL_PASSWORD: exploit2025
    ports:
      - "5000:5000"
    volumes:
      - db-data:/var/lib/mysql
    command: --port=5000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "5000", "-u", "hacker", "-pexploit2025"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "9000:9000"
      - "1337:1337"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: hacker
      DB_PASS: exploit2025
volumes:
  db-data: