spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:db}:5000/hackfest?allowPublicKeyRetrieval=true
    username: ${DB_USER:hacker}
    password: ${DB_PASS:exploit2025}
  jpa:
    hibernate:
      ddl-auto: create-drop # Create schema on startup
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never # Disable default SQL initialization
  thymeleaf:
    cache: false
  webflux:
    base-path: /api
server:
  port: 9000
  error:
    include-stacktrace: always